/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lobbyMVC;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import utilities.Observable;
import utilities.Observer;

/**
 *
 * @author luiis
 */
public class LobbyView extends javax.swing.JFrame implements Observer{

    private JButton newGameBtn, joinGameBtn;
    private LobbyModel model;
    private JLabel label;
    
    /**
     * Creates new form ChooseMatchView
     */
    public LobbyView(LobbyModel model) {
        initComponents();
        this.model= model;
        setFrameSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(24, 111, 101));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LobbyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LobbyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LobbyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LobbyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LobbyView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable ob, Object context) {
        boolean flag = (boolean)context;
        this.setVisible(flag);
    }
    
    private JButton setButtonSettings(JButton button) {
        button = new JButton();
        button.setBackground(model.getBUTTON_BACKGROUND_COLOR());
        button.setFont(model.getBUTTON_TEXT_FONT());
        button.setForeground(model.getBUTTON_TEXT_COLOR());
        return button;
    }
    
    private void setNewGameButtonSettings() {
        newGameBtn = setButtonSettings(newGameBtn);
        newGameBtn.setText(model.getNEW_GAME_BTN_TEXT());
        newGameBtn.setBounds(model.getNEW_GAME_BTN_BOUNDS());
    }
    private void setJoinGameButtonSettings() {
        joinGameBtn = setButtonSettings(joinGameBtn);
        joinGameBtn.setText(model.getJOIN_GAME_BTN_TEXT());
        joinGameBtn.setBounds(model.getJOIN_GAME_BTN_BOUNDS());
    }

    private void setLabelSettings() {
        label = new JLabel(model.getLABEL_TEXT());
        label.setBounds(model.getLABEL_BOUNDS());
        label.setForeground(model.getLABEL_TEXT_COLOR());
        label.setFont(model.getLABEL_FONT());
    }

    private void setFrameSettings() {
        JPanel panel = new JPanel();
        panel.setLayout(null);

        this.setSize(model.getDIMENSION());
        panel.setSize(model.getDIMENSION());
        panel.setBackground(model.getBACKGROUND_COLOR());

        setNewGameButtonSettings();
        setJoinGameButtonSettings();
        setLabelSettings();

        panel.add(newGameBtn);
        panel.add(joinGameBtn);
        panel.add(label);

        this.getContentPane().add(panel);
    }
}
