/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package startMVC;

import java.awt.BorderLayout;
import java.awt.LayoutManager;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import utilities.Observable;
import utilities.Observer;

/**
 *
 * @author luisa
 */
public class StartView extends javax.swing.JFrame implements Observer{

    private StartModel model;
    private JButton btnIniciar;
    private JLabel label;
    /**
     * Creates new form ViewInicio
     */
    public StartView(StartModel model) {
        initComponents();
        this.model = model;
        setFrameSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addListener(java.awt.event.ActionListener listener){
        this.btnIniciar.addActionListener(listener);
    }
//    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StartView().setVisible(true);
//            }
//        });
//    }
    
    private void setButtonSettings(){
        btnIniciar= new JButton();
        btnIniciar.setBackground(model.getButtonBackgroundColor());
        btnIniciar.setText(model.getbuttonText());
        btnIniciar.setFont(model.getButtonTextFont());
        btnIniciar.setForeground(model.getButtonTextColor());
        btnIniciar.setBounds(model.getButtonBounds());
    }
    
    private void setLabelSettings(){
        label = new JLabel(model.getLabelText());
        label.setBounds(model.getLabelBounds());
        label.setForeground(model.getLabelTextColor());
        label.setFont(model.getLabelFont());
    }
    
    private void setFrameSettings(){
        JPanel panel = new JPanel();
        panel.setLayout(null);
        
        this.setSize(model.getDimension());
        panel.setSize(model.getDimension());
        panel.setBackground(model.getBackgroundColor());
        
        setButtonSettings();
        setLabelSettings();
        
        panel.add(btnIniciar);
        panel.add(label);
        
        this.getContentPane().add(panel);
    }

    @Override
    public void update(Observable ob, Object context) {
        boolean flag = (boolean)context;
        this.setVisible(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
